fix: missing gh command and deprecated set-output

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -39,11 +39,11 @@ jobs:
           sudo mkdir -p src/fhem-mirror
           sudo mount -t tmpfs -o size=1g tmpfs src/fhem-mirror
 
-      - name: install git-svn package
+      - name: install git-svn and gh package
         run: |
           sudo apt-get remove git git-man
           sudo apt-get update
-          sudo apt-get install subversion git-svn -y --no-install-recommends
+          sudo apt-get install subversion git-svn gh -y --no-install-recommends
 
       - name: checkout authors
         uses: actions/checkout@v5.0.0
@@ -61,7 +61,7 @@ jobs:
       - name: Get current date 
         id: get-date
         run: |
-          echo "::set-output name=timestamp::$(/bin/date -u "+%Y%m%d%H" )"
+          echo "timestamp=$(/bin/date -u "+%Y%m%d%H" )" >> $GITHUB_OUTPUT
         shell: bash
 
       - name: Cache runners svn-2-git-fhem mirror directory  
@@ -93,21 +93,21 @@ jobs:
           cat ${GITHUB_WORKSPACE}/src/fhem-mirror/.git/config;
           echo "::endgroup::"
           
-          echo "::set-output name=SVN_FETCH_STATUS::incomplete"
+          echo "SVN_FETCH_STATUS=incomplete" >> $GITHUB_OUTPUT
           # Run fetches after init, go pick up some base refs for the cache on first run only!
           RET=124
           c=1
           while [ $RET -eq 124 ]; do
             echo "::group::Fetch ${c}/5"
-            timeout 60 git svn --log-window-size=200 -q fetch && RET=$? || true
+            timeout 12 git svn --log-window-size=200 -q fetch && RET=$? || true
             if [ "$RET" -ne 0 ] && [ "$RET" -ne 124 ]; then
-              echo "::set-output name=SVN_FETCH_STATUS::error"
+              echo "SVN_FETCH_STATUS=error" >> $GITHUB_OUTPUT
             fi 
             ((c++)) && ((c==6)) && break
             echo "::endgroup::"
           done
           if [ "$RET" -eq 0 ]; then          
-            echo "::set-output name=SVN_FETCH_STATUS::complete"
+            echo "SVN_FETCH_STATUS=complete" >> $GITHUB_OUTPUT
           fi
 
      # - name: Copy Workflow Files to target
