fix: groups and gc

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -124,7 +124,7 @@ jobs:
         timeout-minutes: 120
         working-directory: ./src/fhem-mirror
         run: |
-          echo "::group::prepare"  
+          echo "::group::prepare"
           FETCH_TIMEOUT=${{ inputs.fetch_timeout }}
           if [[ "${{ github.ref }}" != "refs/heads/main" && "$FETCH_TIMEOUT" == "1201" ]]; then
             FETCH_TIMEOUT=30
@@ -145,19 +145,12 @@ jobs:
             echo "::endgroup::"
             ((c++)) && ((c > ${{ inputs.max_attempts }})) && break
           done
+          echo "::group::finish"
           if [ "$RET" -eq 0 ]; then       
-            echo "SVN_FETCH_STATUS=complete" >> $GITHUB_OUTPUT
+            git gc && echo "SVN_FETCH_STATUS=complete" >> $GITHUB_OUTPUT || echo "SVN_FETCH_STATUS=error" >> $GITHUB_OUTPUT
           fi
-
-      - name: Create main branch if it does not exist in cache
-        if: always() && steps.fetchsvn.outputs.SVN_FETCH_STATUS != 'error'
-        working-directory: ./src/fhem-mirror
-        run: |
-          if ! git show-ref --verify --quiet refs/heads/main; then
-            # main branch should be a copy of the svn trunk after fetch
-            git branch main svn/trunk
-          fi
-          
+          echo "::endgroup::"
+       
       - name: Checkout repository for gh CLI
         if: always()
         uses: actions/checkout@v5
